package com.interstellar.elite.core.response

import com.interstellar.elite.core.APIResponse

data class PolicyBossVehicleInfoResponse(
    val Call_Execution_Time: Double,
    val CarVariantName: String,
    val Chassis_Number: String,
    val CityofRegitration: String,
    val CityofRegitrationId: Int,
    val Color: String,
    val Cubic_Capacity: String,
    val Engin_Number: String,
    val ErrorMessage: String,
    val FastLaneId: Int,
    val FastlanePostResponse: String,
    val FastlaneResponse: String,
    val FuelName: String,
    val Fuel_ID: Int,
    val Fuel_Type: String,
    val Is_LM: String,
    val Make_ID: Int,
    val Make_Name: String,
    val ManufactureYear: String,
    val Manufacture_Year: Int,
    val ModelID: Int,
    val ModelName: String,
    val Model_ID: Int,
    val Model_Name: String,
    val PD_VehicleCity_Id: Int,
    val PoExpiryDuration: String,
    val Purchase_Date: String,
    val RTO_Code: Int,
    val RTO_Name: String,
    val RegistrationDate: String,
    val Registration_Date: String,
    val Registration_Number: String,
    val Seating_Capacity: Int,
    val Source: String,
    val VariantId: Int,
    val Variant_Id: Int,
    val Variant_Name: String,
    val VehicleCity_Id: Int,
    val Year: Int,
    val citycamal: String,

):APIResponse()